import numpy as np
#!/usr/bin/env python3
"""
AEGIS 3.0 Robust Validation Suite — Master Test Runner

Runs all 43 tests across 7 test files and auto-generates
VALIDATION_REPORT.md with consistent numbers.

Usage:
    cd /Users/abishaikc/Desktop/Miniproject/robust_validation
    python3 run_all.py
"""

import sys, os
import json
import traceback
from datetime import datetime

# Ensure we can import our modules
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from tests import test_layer1, test_layer2, test_layer3, test_layer4, test_layer5
from tests import test_integration, test_adversarial


def run_suite(name, module):
    """Run a test suite and return results with error handling."""
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")
    try:
        results = module.run_all_tests()
        passed = sum(1 for r in results if r['passed'])
        total = len(results)
        print(f"\n  → {name}: {passed}/{total} passed")
        return results
    except Exception as e:
        print(f"\n  ✗ {name} FAILED WITH ERROR: {e}")
        traceback.print_exc()
        return [{
            'test_id': f'{name}-ERROR',
            'name': f'{name} execution error',
            'type': 'error',
            'metrics': {'error': str(e)},
            'passed': False,
        }]


def generate_report(all_results, elapsed_seconds):
    """Auto-generate VALIDATION_REPORT.md from test results."""
    timestamp = datetime.now().isoformat()

    # Aggregate stats
    total = sum(len(r) for r in all_results.values())
    passed = sum(sum(1 for t in r if t['passed']) for r in all_results.values())
    failed = total - passed

    nominal_tests = []
    robust_tests = []
    adversarial_tests = []
    for suite_results in all_results.values():
        for t in suite_results:
            if t.get('type') == 'nominal':
                nominal_tests.append(t)
            elif t.get('type') == 'robust':
                robust_tests.append(t)
            elif t.get('type') in ('adversarial',):
                adversarial_tests.append(t)

    nominal_passed = sum(1 for t in nominal_tests if t['passed'])
    robust_passed = sum(1 for t in robust_tests if t['passed'])
    adv_passed = sum(1 for t in adversarial_tests if t['passed'])

    report = f"""# AEGIS 3.0 Robust Validation Report

**Generated:** {timestamp}
**Runtime:** {elapsed_seconds:.1f} seconds
**Suite Version:** Robust Validation v1.0

---

## Summary

| Category | Passed | Total | Rate |
|----------|--------|-------|------|
| **Nominal** | {nominal_passed} | {len(nominal_tests)} | {nominal_passed/max(len(nominal_tests),1)*100:.0f}% |
| **Robustness** | {robust_passed} | {len(robust_tests)} | {robust_passed/max(len(robust_tests),1)*100:.0f}% |
| **Adversarial** | {adv_passed} | {len(adversarial_tests)} | {adv_passed/max(len(adversarial_tests),1)*100:.0f}% |
| **Overall** | **{passed}** | **{total}** | **{passed/max(total,1)*100:.1f}%** |

---

## Per-Layer Results

"""
    for suite_name, suite_results in all_results.items():
        sp = sum(1 for t in suite_results if t['passed'])
        st = len(suite_results)
        report += f"### {suite_name} ({sp}/{st})\n\n"
        report += "| ID | Name | Type | Status |\n"
        report += "|-----|------|------|--------|\n"
        for t in suite_results:
            status = "✅ PASS" if t['passed'] else "❌ FAIL"
            report += f"| {t['test_id']} | {t['name']} | {t['type']} | {status} |\n"
        report += "\n"

    report += """---

## Detailed Metrics

"""
    for suite_name, suite_results in all_results.items():
        report += f"### {suite_name}\n\n"
        for t in suite_results:
            status = "✅" if t['passed'] else "❌"
            report += f"**{t['test_id']}: {t['name']}** {status}\n\n"
            metrics = t.get('metrics', {})
            for k, v in metrics.items():
                if isinstance(v, float):
                    report += f"- {k}: `{v:.4f}`\n"
                elif isinstance(v, dict):
                    report += f"- {k}:\n"
                    for kk, vv in v.items():
                        if isinstance(vv, float):
                            report += f"  - {kk}: `{vv:.4f}`\n"
                        else:
                            report += f"  - {kk}: `{vv}`\n"
                elif isinstance(v, list) and len(v) < 10:
                    report += f"- {k}: `{v}`\n"
                else:
                    report += f"- {k}: `{v}`\n"
            report += "\n"

    report += f"""---

## Validation Notes

1. **Independent Data Generation:** Patient data generated by Hovorka model
   (structurally different from Bergman used by Digital Twin)
2. **Causal Structure:** Proxy variables Z, W satisfy conditional independence
   by construction in the data generating process
3. **Cold Start:** Alpha relaxation verified with real data accumulation
4. **No Mocks:** All layers use real implementations (PyTorch MLP, UKF,
   KernelRidge, etc.)
5. **Reproducibility:** All tests use fixed seeds from config.py

## Test Environment

- Timestamp: {timestamp}
- Runtime: {elapsed_seconds:.1f}s
"""

    # Failed tests detail
    failed_tests = [t for suite in all_results.values() for t in suite if not t['passed']]
    if failed_tests:
        report += "\n## Failed Tests Detail\n\n"
        for t in failed_tests:
            report += f"### {t['test_id']}: {t['name']}\n\n"
            report += f"- Type: {t['type']}\n"
            report += f"- Metrics: {json.dumps(t.get('metrics', {}), indent=2, default=str)}\n"
            if 'threshold' in t:
                report += f"- Threshold: {json.dumps(t['threshold'], indent=2, default=str)}\n"
            report += "\n"

    return report


def main():
    import time
    start = time.time()

    print("╔════════════════════════════════════════════════════════╗")
    print("║       AEGIS 3.0 — Robust Validation Suite v1.0       ║")
    print("║       43 Tests · 7 Suites · Real Implementations     ║")
    print("╚════════════════════════════════════════════════════════╝")

    all_results = {}

    suites = [
        ("Layer 1: Semantic Sensorium", test_layer1),
        ("Layer 2: Digital Twin", test_layer2),
        ("Layer 3: Causal Inference", test_layer3),
        ("Layer 4: Decision Engine", test_layer4),
        ("Layer 5: Safety Supervisor", test_layer5),
        ("Integration Tests", test_integration),
        ("Adversarial Tests", test_adversarial),
    ]

    for name, module in suites:
        all_results[name] = run_suite(name, module)

    elapsed = time.time() - start

    # Final summary
    total = sum(len(r) for r in all_results.values())
    passed = sum(sum(1 for t in r if t['passed']) for r in all_results.values())

    print(f"\n{'='*60}")
    print(f"  FINAL RESULTS: {passed}/{total} tests passed ({passed/max(total,1)*100:.1f}%)")
    print(f"  Runtime: {elapsed:.1f}s")
    print(f"{'='*60}")

    for name, suite_results in all_results.items():
        sp = sum(1 for t in suite_results if t['passed'])
        st = len(suite_results)
        icon = "✅" if sp == st else "⚠️"
        print(f"  {icon} {name}: {sp}/{st}")

    # Generate report
    report = generate_report(all_results, elapsed)
    report_path = os.path.join(os.path.dirname(__file__), 'VALIDATION_REPORT.md')
    with open(report_path, 'w') as f:
        f.write(report)
    print(f"\n  📄 Report saved to: {report_path}")

    # Save raw JSON
    json_path = os.path.join(os.path.dirname(__file__), 'results.json')
    json_results = {}
    for name, suite in all_results.items():
        json_results[name] = []
        for t in suite:
            # Convert numpy types for JSON serialization
            clean = {}
            for k, v in t.items():
                if isinstance(v, dict):
                    clean[k] = {kk: float(vv) if hasattr(vv, '__float__') and not isinstance(vv, bool)
                                else bool(vv) if isinstance(vv, (bool, np.bool_)) else str(vv)
                                if not isinstance(vv, (str, int, float, bool, list, dict, type(None))) else vv
                                for kk, vv in v.items()}
                else:
                    clean[k] = v
            json_results[name].append(clean)

    try:

        class NumpyEncoder(json.JSONEncoder):
            def default(self, obj):
                if isinstance(obj, (np.integer,)):
                    return int(obj)
                if isinstance(obj, (np.floating,)):
                    return float(obj)
                if isinstance(obj, (np.bool_,)):
                    return bool(obj)
                if isinstance(obj, np.ndarray):
                    return obj.tolist()
                return super().default(obj)

        with open(json_path, 'w') as f:
            json.dump(json_results, f, indent=2, cls=NumpyEncoder)
        print(f"  📊 Raw results saved to: {json_path}")
    except Exception as e:
        print(f"  ⚠️  Could not save JSON: {e}")

    # Exit code
    exit_code = 0 if passed == total else 1
    return exit_code


if __name__ == '__main__':
    sys.exit(main())
